### ISSUE TITLE
Shared Memory Sync in Multiple Connections Scenario

### ISSUE THREAD

**Issue by Chikdolman** [Samsung/Castanets#142]
The current implementation of syncing shared memory between a browser process and a renderer process is acceptable for 1:1 scenario
However, further implementations and modifications are required for syncing shared memory between a browser process and multiple renderer processes (1:N).

**Comment by hyowon** [comment]
Two important requirements

1. We send sync messages via the broker channel, so the broker channels should be managed in a similar way as the node channels.
2. Whenever we perform synchronization on each shared memory, we should be able to find a node that is sharing it.

**Comment by hyowon** [comment]
PRs https://github.com/Samsung/Castanets/pull/152 https://github.com/Samsung/Castanets/pull/154
