### ISSUE TITLE
Broken tiles are shown.

### ISSUE THREAD

**Issue by hyowon** [Samsung/Castanets#147]
- Some tiles show black or stale bitmaps.
- It can be easily found on complex web pages. (www.daum.net)
- It doesn't occur if preventing the resource manager from reusing tile resources.
- It occurs in both SW and GPU compositing.

**Comment by Sunwoo-Nam** [comment]
This issue occurs when resources are reused for tiles of different sizes.
If a mapped shared memory size is bigger than a tile size,
memory sync should be done with full shared memory size.
Memory sync is not supporting partial sync.

https://github.com/Samsung/Castanets/pull/148

**Comment by Sunwoo-Nam** [comment]
Fixed by https://github.com/Samsung/Castanets/pull/148
