### ISSUE TITLE
Fallback to the child process launcher when facing Castanets connection timeout.

### ISSUE THREAD

**Issue by hyowon** [Samsung/Castanets#156]
Adding the fallback function itself makes sense. In addition, two types of child process connections can be run simultaneously in one browser - TCP/IP based castanets connection and IPC based existing connection.

**Comment by joonghunpark** [comment]
This issue has been resolved with https://github.com/Samsung/Castanets/commit/a28f1d749b721f25bebfc4583b38cd5b84026820.
