### ISSUE TITLE
[Performance][Refactor] Synchronization Controls for GPU Transfer Buffer.

### ISSUE THREAD

**Issue by hyowon** [Samsung/Castanets#159]
See https://github.com/Samsung/Castanets/pull/153#pullrequestreview-266458979

- Investigate whether GpuChannelMsg_RequestSyncTransferBuffer can be removed.
- Analysis for Sync call minimization

**Comment by Sunwoo-Nam** [comment]
https://github.com/Samsung/Castanets/pull/162 (being reviewed)

**Comment by Sunwoo-Nam** [comment]
There are gpu commands which initialize a result value to non-zero.
GetAttribLocationHelper
GetUniformLocationHelper
GetFragDataIndexEXTHelper
GetFragDataLocationHelper
GetUniformBlockIndexHelper
ClientWaitSync
GetShaderPrecisionFormat

**Comment by Sunwoo-Nam** [comment]
Pass on to the next issue if the non-zero value causes a problem.
