### ISSUE TITLE
[Performance] Shared Memory Allocation on Android

### ISSUE THREAD

**Issue by hyowon** [Samsung/Castanets#163]
See https://github.com/Samsung/Castanets/issues/124#issuecomment-512675861.
In my humble opinion, we should use ashmem_create_region() for SharedMemory on Android. We will have to implement the Android version of CreateAnonymousSharedMemoryIfNeeded().

**Comment by suyambulingamrm** [comment]
As a initial step, I handled android case to use ashmem https://github.com/Samsung/Castanets/pull/169.
On verification, the change seems to be working fine. We can verify the ashmem data from meminfo dump.
Before using ashmem,
![image](https://user-images.githubusercontent.com/6712167/62132093-065f7c80-b2fa-11e9-97d8-351b76067350.png)
After using ashmem,
![image](https://user-images.githubusercontent.com/6712167/62132182-30b13a00-b2fa-11e9-8e65-3783073e2e76.png)

**Comment by suyambulingamrm** [comment]
Visibly loading, scrolling performance improved after using ashmem.
https://github.com/Samsung/Castanets/pull/169
