### ISSUE TITLE
Check failed with gpu composing

### ISSUE THREAD

**Issue by is46-kim** [Samsung/Castanets#176]
Check failed with gpu composing on linux. It causes a crash.
This check failure does not occur with "--disable-gpu-compositing" command line option.

< Backtrace >
[3228:3237:0806/173630.380276:FATAL:gles2_implementation.cc(1170)] Check failed: query->CheckResultsAvailable(helper_). 

#0 0x7f224b0e493c base::debug::StackTrace::StackTrace()
#1 0x7f224b045d40 logging::LogMessage::~LogMessage()
#2 0x7f223e489aa4 gpu::gles2::GLES2Implementation::GetQueryObjectValueHelper()
#3 0x7f223e49c249 gpu::gles2::GLES2Implementation::GetQueryObjectuivEXT()
#4 0x7f223e63667d cc::StagingBufferPool::AcquireStagingBuffer()
#5 0x7f223e631d09 cc::OneCopyRasterBufferProvider::PlaybackAndCopyOnWorkerThread()
#6 0x7f223e631bb1 cc::OneCopyRasterBufferProvider::RasterBufferImpl::Playback()
#7 0x7f223e675774 cc::(anonymous namespace)::RasterTaskImpl::RunOnWorkerThread()
#8 0x7f224919b6bc content::CategorizedWorkerPool::RunTaskInCategoryWithLockAcquired()
#9 0x7f224919a54a content::CategorizedWorkerPool::Run()
#10 0x7f224b0b7324 base::SimpleThread::ThreadMain()
#11 0x7f224b0f26ed base::(anonymous namespace)::ThreadFunc()
#12 0x7f2241ed36ba start_thread
#13 0x7f223fe4e41d clone

**Comment by Sunwoo-Nam** [comment]
We can skip the Check() temporarily like version 63.
But after that, the below crash occurs on browser process.
It seems that BrokerCastanets is not valid.

Received signal 11 SEGV_MAPERR 00000000003f
#0 0x7f2d74f38eac base::debug::StackTrace::StackTrace()
#1 0x7f2d74f38a01 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f2d6bb6f390 <unknown>
#3 0x7f2d69a78a10 <unknown>
#4 0x7f2d6675c1ed mojo::core::BrokerCastanets::OnBufferSync()
#5 0x7f2d6675cb42 mojo::core::BrokerCastanets::OnChannelMessage()
#6 0x7f2d6673703f mojo::core::Channel::OnReadComplete()
#7 0x7f2d66758497 mojo::core::(anonymous namespace)::ChannelPosix::OnFileCanReadWithoutBlocking()
#8 0x7f2d74f4bd2b base::MessagePumpLibevent::OnLibeventNotification()
#9 0x7f2d74f64a8d event_base_loop
#10 0x7f2d74f4bfee base::MessagePumpLibevent::Run()
#11 0x7f2d74ec0195 base::RunLoop::Run()
#12 0x7f2d729c4914 content::BrowserProcessSubThread::IOThreadRun()
#13 0x7f2d74f048af base::Thread::ThreadMain()
#14 0x7f2d74f4ec87 base::(anonymous namespace)::ThreadFunc()
#15 0x7f2d6bb656ba start_thread
#16 0x7f2d69ae041d clone

**Comment by Sunwoo-Nam** [comment]
Temporarily, I disabled the GPU compositing.
https://github.com/Samsung/Castanets/pull/177

I'm going to continue to analyze the issue.

**Comment by is46-kim** [comment]
When crash occurs with GPU compositing in my machine, the code of  signal 11 is  SEGV_ACCERR.
This code means Invalid Permissions for object.
> [6664:6667:0822/095206.313467:INFO:broker_castanets.cc(246)] OnBufferSync()0x7f3e661e8000, of:0, bytes:262144
> Received signal 11 **SEGV_ACCERR** 7f3e661e8000

This crash caused by the read only memory.
The crash can be fixed by removing the read only flag in mmap () at SharedMemory::MapAt().

> mmap(nullptr, bytes, PROT_READ | (**/*read_only_ ? 0 :*/** PROT_WRITE),
>                  MAP_SHARED, shm_.GetHandle(), offset);

**Comment by Sunwoo-Nam** [comment]
Fixed by https://github.com/Samsung/Castanets/pull/198
