### ISSUE TITLE
Castanets 76 does not work between a Tizen TV and an Ubuntu desktop.

### ISSUE THREAD

**Issue by Sunwoo-Nam** [Samsung/Castanets#302]
[ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 5

They are connected but 
I suspect the IPC problem between a tv and a desktop.

The TV and Android scenario doesn't have this problem.

**Comment by Sunwoo-Nam** [comment]
This is a sub-issue of https://github.com/Samsung/Castanets/issues/302

**Comment by suyambulingamrm** [comment]
Regarding tizen-desktop case, there is a dependency with VizDisplayCompositor feature. Efl port doesnt support VizDisplayCompositor.
Desktop shows white screen if we disable VizDisplayCompositor (This happens in noncastanets upstream too).

So for CASTANETS && ANDROID case, we disabled VizDisplayCompositor in components/viz/common/features.cc.

As a workaround for now , we can specifically enable/disable the feature accordingly when we test desktop-android/tizen.

desktop(B)-desktop(R) no additional flags
tizen(B)-android(R) no additional flags
desktop(B)-android(R) (--enable-features="VizDisplayCompositor" in android)
tizen(B)-desktop(R) (--disable-features="VizDisplayCompositor" in desktop)

**Comment by Sunwoo-Nam** [comment]
@suyambulingamrm 
It seems that the only solution is to figure out a device type and apply the feature in runtime..
Thanks for letting us know.

**Comment by Chikdolman** [comment]
Close issue as it is resolved with the flag.
