### ISSUE TITLE
Crash In "yahoo.com"

### ISSUE THREAD

**Issue by Sunwoo-Nam** [Samsung/Castanets#324]
TV(BP) <-> Android(RP)

The crash issue occurs while loading.

F chromium: [FATAL:castanets_memory_syncer.cc(28)] Check failed: !mapping_info_.

**Comment by Sunwoo-Nam** [comment]
Stack Trace:
  RELADDR   FUNCTION                                                                          FILE:LINE
  000603ca  <UNKNOWN>                                                                         /apex/com.android.runtime/lib/bionic/libc.so
  v------>  base::debug::(anonymous namespace)::DebugBreak()                                  ../../base/debug/debugger_posix.cc:280:5
  019250af  base::debug::BreakDebugger()                                                      ../../base/debug/debugger_posix.cc:313:0
  018c8e45  logging::LogMessage::~LogMessage()                                                ../../base/logging.cc:939:7
  0192ccc1  base::UnknownMemorySyncer::SetMappingInfo(scoped_refptr<base::CastanetsMemoryMapping>)  ../../base/memory/castanets_memory_syncer.cc:28:3
  018cb573  base::SharedMemoryTracker::AddMapping(base::UnguessableToken const&, unsigned int, void*)  ../../base/memory/shared_memory_tracker.cc:187:27
  018cb277  base::CastanetsMemoryHolder::CastanetsMemoryHolder(base::subtle::PlatformSharedMemoryRegion)  ../../base/memory/shared_memory_tracker.cc:47:39
  v------>  std::__1::pair<base::UnguessableToken const, base::CastanetsMemoryHolder>::pair<base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion, false>(base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion&&)  ../../buildtools/third_party/libc++/trunk/include/utility:450:45
  v------>  void std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, void*> >::construct<std::__1::pair<base::UnguessableToken const, base::CastanetsMemoryHolder>, base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion>(std::__1::pair<base::UnguessableToken const, base::CastanetsMemoryHolder>*, base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion&&)  ../../buildtools/third_party/libc++/trunk/include/memory:1825:0
  v------>  void std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, void*> > >::__construct<std::__1::pair<base::UnguessableToken const, base::CastanetsMemoryHolder>, base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion>(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, void*> >&, std::__1::pair<base::UnguessableToken const, base::CastanetsMemoryHolder>*, base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion&&)  ../../buildtools/third_party/libc++/trunk/include/memory:1717:0
  v------>  void std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, void*> > >::construct<std::__1::pair<base::UnguessableToken const, base::CastanetsMemoryHolder>, base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion>(std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, void*> >&, std::__1::pair<base::UnguessableToken const, base::CastanetsMemoryHolder>*, base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion&&)  ../../buildtools/third_party/libc++/trunk/include/memory:1560:0
  v------>  std::__1::unique_ptr<std::__1::__tree_node<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, void*>, std::__1::__tree_node_destructor<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, void*> > > > std::__1::__tree<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, std::__1::__map_value_compare<base::UnguessableToken, std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, std::__1::less<base::UnguessableToken>, true>, std::__1::allocator<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder> > >::__construct_node<base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion>(base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion&&)  ../../buildtools/third_party/libc++/trunk/include/__tree:2218:0
  018cd07f  std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, std::__1::__tree_node<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, void*>*, int>, bool> std::__1::__tree<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, std::__1::__map_value_compare<base::UnguessableToken, std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, std::__1::less<base::UnguessableToken>, true>, std::__1::allocator<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder> > >::__emplace_unique_key_args<base::UnguessableToken, base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion>(base::UnguessableToken const&, base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion&&)  ../../buildtools/third_party/libc++/trunk/include/__tree:2163:0
  v------>  std::__1::enable_if<__can_extract_map_key<base::UnguessableToken const&, base::UnguessableToken, std::__1::pair<base::UnguessableToken const, base::CastanetsMemoryHolder> >::value, std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, std::__1::__tree_node<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, void*>*, int>, bool> >::type std::__1::__tree<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, std::__1::__map_value_compare<base::UnguessableToken, std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, std::__1::less<base::UnguessableToken>, true>, std::__1::allocator<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder> > >::__emplace_unique<base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion>(base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion&&)  ../../buildtools/third_party/libc++/trunk/include/__tree:1179:16
  v------>  std::__1::pair<std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, std::__1::__tree_node<std::__1::__value_type<base::UnguessableToken, base::CastanetsMemoryHolder>, void*>*, int> >, bool> std::__1::map<base::UnguessableToken, base::CastanetsMemoryHolder, std::__1::less<base::UnguessableToken>, std::__1::allocator<std::__1::pair<base::UnguessableToken const, base::CastanetsMemoryHolder> > >::emplace<base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion>(base::UnguessableToken const&, base::subtle::PlatformSharedMemoryRegion&&)  ../../buildtools/third_party/libc++/trunk/include/map:1148:0
  018cc95d  base::SharedMemoryTracker::AddHolder(base::subtle::PlatformSharedMemoryRegion)    ../../base/memory/shared_memory_tracker.cc:342:0
  018caed3  base::CreateAnonymousSharedMemoryIfNeeded(base::UnguessableToken const&, base::SharedMemoryCreateOptions const&)  ../../base/memory/shared_memory_helper.cc:229:39
  00d9035f  mojo::core::BrokerCastanets::OnBufferSync(unsigned long long, unsigned long long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, void const*)  ../../mojo/core/broker_castanets.cc:542:7
  00d90c65  mojo::core::BrokerCastanets::OnChannelMessage(void const*, unsigned int, std::__1::vector<mojo::PlatformHandle, std::__1::allocator<mojo::PlatformHandle> >)  ../../mojo/core/broker_castanets.cc:868:9
  00d7dd2d  mojo::core::Channel::TryDispatchMessage(base::span<char const, 4294967295u>, unsigned int*)  ../../mojo/core/channel.cc:791:16
  00d7dbab  mojo::core::Channel::OnReadComplete(unsigned int, unsigned int*)                  ../../mojo/core/channel.cc:689:9
  00d8eb07  mojo::core::(anonymous namespace)::ChannelCastanets::ReadFDWithoutBlocking()      ../../mojo/core/channel_posix.cc:969:14
  v------>  base::OnceCallback<void ()>::Run() &&                                             ../../base/callback.h:97:12
  018ed79f  base::TaskAnnotator::RunTask(char const*, base::PendingTask*)                     ../../base/task/common/task_annotator.cc:142:0
  018fdec3  base::internal::TaskTracker::RunSkipOnShutdown(base::internal::Task*)             ../../base/task/thread_pool/task_tracker.cc:746:19
  v------>  base::internal::TaskTracker::RunTaskWithShutdownBehavior(base::TaskShutdownBehavior, base::internal::Task*)  ../../base/task/thread_pool/task_tracker.cc:764:7
  018fdb65  base::internal::TaskTracker::RunOrSkipTask(base::internal::Task, base::internal::TaskSource*, base::TaskTraits const&, bool)  ../../base/task/thread_pool/task_tracker.cc:596:0
  0192c5c5  base::internal::TaskTrackerPosix::RunOrSkipTask(base::internal::Task, base::internal::TaskSource*, base::TaskTraits const&, bool)  ../../base/task/thread_pool/task_tracker_posix.cc:24:16
  018fd8af  base::internal::TaskTracker::RunAndPopNextTask(base::internal::RegisteredTaskSource)  ../../base/task/thread_pool/task_tracker.cc:458:5
  01901595  base::internal::WorkerThread::RunWorker()                                         ../../base/task/thread_pool/worker_thread.cc:320:34
  019014b7  base::internal::WorkerThread::RunDedicatedWorker()                                ../../base/task/thread_pool/worker_thread.cc:246:3
  0192c929  base::(anonymous namespace)::ThreadFunc(void*)                                    ../../base/threading/platform_thread_posix.cc:81:13
  000a75b3  <UNKNOWN>                                                                         /apex/com.android.runtime/lib/bionic/libc.so
  00061b33  <UNKNOWN>                                                                         /apex/com.android.runtime/lib/bionic/libc.so

**Comment by suyambulingamrm** [comment]
I checked yahoo.com on tv(ubrowser) and android(renderer) on latest source.
yahoo.com redirects to https://in.yahoo.com/?p=us in my environment.
Basic page load and scroll seems to be ok and I could not observe the crash.

**Comment by Sunwoo-Nam** [comment]
@suyambulingamrm 
I checked https://in.yahoo.com/?p=us and it was fine.

I can just see the below URL in the crash case.
APP.C callback called __uri_changed_cb URI is = https://www.yahoo.com/

**Comment by suyambulingamrm** [comment]
I can reproduce the issue with ubrowser/efl_webview_app when loading https://yahoo.com/?p=dnr.
But there was a strange observation. I backed up and deleted **/opt/usr/home/owner/.config/chromium-efl/**  in TV which contains caches and db related configurations.
After that I am no longer able to reproduce the crash, even after restoring the backed up folder.

On checking further, I obseverved below, 
Scenario: (efl_webview_app)
1. rm -rf /opt/usr/home/owner/.config/chromium-efl/Service\ Worker/ScriptCache/
2. load yahoo.com/?p=dnr in castanets mode, TV-android => no crash on multiple trials
3. load yahoo.com/?p=dnr in standlone mode (once) => page loads fine
4. load yahoo.com/?p=dnr in castanets mode, TV-android => crash on load.

Looks like loading some cached resource in castanets mode is causing crash.

**Comment by suyambulingamrm** [comment]
The changes to disable disk cache for script caching in service worker is disable in browser side.
The crash is no longer observed,
Hence the issue can be closed.
