### ISSUE TITLE
The "Chromie" macro needs to be changed to "Castanets"

### ISSUE THREAD

**Issue by Sunwoo-Nam** [Samsung/Castanets#5]
The project name was decided "Castanets", so the macros and the flags should be changed.

**Comment by suyambulingamrm** [comment]
For M63 branch, https://github.com/Samsung/Castanets/commits/castanets_63
enable_castanets build flag is used and macro is changed accordingly.
So we can close this issue I think.

**Comment by Sunwoo-Nam** [comment]
This is closed by cc32d089c37dc71229b1f12af0e5851ff2d24fe8
