### ISSUE TITLE
Share Command Buffer and One-Copy Texture for GPU Compositing.

### ISSUE THREAD

**Issue by Sunwoo-Nam** [Samsung/Castanets#94]
On castanets_63 branch, GPU channel is enabled and GPU rasterizing and WebGL are able to be run. (MM video is not still shown with GPU)

Now, migrating GPU channel to 69 is necessary, but the implementation of shared memory for castanets was changed since castanets_69.

**Comment by hyowon** [comment]
#15 same issue?

**Comment by Sunwoo-Nam** [comment]
@hyowon This issue can be understood as more specific to #15 .
I just think #15 is too old and implementation has almost done on 63, so I want to talk about the next step (version 69).

**Comment by hyowon** [comment]
See https://github.com/Samsung/Castanets/commit/bc256f8b50d571c99214506d5ed808555d403fb6 ,https://github.com/Samsung/Castanets/commit/98a63958edf9adb6a7e026a492762e79a13e40f9.
For now, we can get a valid shared memory from a command buffer and a GPU image. And Tracker is also tracking their mapping information. The only thing we have to do is to call sync.

**Comment by Sunwoo-Nam** [comment]
Fixed by https://github.com/Samsung/Castanets/pull/107,  https://github.com/Samsung/Castanets/pull/148
